#include "mkv.h"

mkv_register_t mkv_register_id(uint32_t id) {
	switch(id) {
		case ELEMENT_EBML:
			return ElementEBML;
		case ELEMENT_EBML_VERSION:
			return ElementEBMLVersion;
		case ELEMENT_EBML_READ_VERSION:
			return ElementEBMLReadVersion;
		case ELEMENT_EBML_MAX_ID_LENGTH:
			return ElementEBMLMaxIDLength;
		case ELEMENT_EBML_MAX_SIZE_LENGTH:
			return ElementEBMLMaxSizeLength;
		case ELEMENT_DOC_TYPE:
			return ElementDocType;
		case ELEMENT_DOC_TYPE_VERSION:
			return ElementDocTypeVersion;
		case ELEMENT_DOC_TYPE_READ_VERSION:
			return ElementDocTypeReadVersion;
		case ELEMENT_VOID:
			return ElementVoid;
		case ELEMENT_CRC32:
			return ElementCRC32;
		case ELEMENT_SEGMENT:
			return ElementSegment;
		case ELEMENT_SEEK_HEAD:
			return ElementSeekHead;
		case ELEMENT_SEEK:
			return ElementSeek;
		case ELEMENT_SEEK_ID:
			return ElementSeekID;
		case ELEMENT_SEEK_POSITION:
			return ElementSeekPosition;
		case ELEMENT_INFO:
			return ElementInfo;
		case ELEMENT_TIMECODE_SCALE:
			return ElementTimecodeScale;
		case ELEMENT_DURATION:
			return ElementDuration;
		case ELEMENT_DATE_UTC:
			return ElementDateUTC;
		case ELEMENT_TITLE:
			return ElementTitle;
		case ELEMENT_MUXING_APP:
			return ElementMuxingApp;
		case ELEMENT_WRITING_APP:
			return ElementWritingApp;
		case ELEMENT_CLUSTER:
			return ElementCluster;
		case ELEMENT_TIMECODE:
			return ElementTimecode;
		case ELEMENT_PREV_SIZE:
			return ElementPrevSize;
		case ELEMENT_SIMPLE_BLOCK:
			return ElementSimpleBlock;
		case ELEMENT_BLOCK_GROUP:
			return ElementBlockGroup;
		case ELEMENT_BLOCK:
			return ElementBlock;
		case ELEMENT_BLOCK_ADDITIONS:
			return ElementBlockAdditions;
		case ELEMENT_BLOCK_MORE:
			return ElementBlockMore;
		case ELEMENT_BLOCK_ADD_ID:
			return ElementBlockAddID;
		case ELEMENT_BLOCK_ADDITIONAL:
			return ElementBlockAdditional;
		case ELEMENT_BLOCK_DURATION:
			return ElementBlockDuration;
		case ELEMENT_REFERENCE_BLOCK:
			return ElementReferenceBlock;
		case ELEMENT_DISCARD_PADDING:
			return ElementDiscardPadding;
		case ELEMENT_TRACKS:
			return ElementTracks;
		case ELEMENT_TRACK_ENTRY:
			return ElementTrackEntry;
		case ELEMENT_TRACK_NUMBER:
			return ElementTrackNumber;
		case ELEMENT_TRACK_UID:
			return ElementTrackUID;
		case ELEMENT_TRACK_TYPE:
			return ElementTrackType;
		case ELEMENT_FLAG_ENABLED:
			return ElementFlagEnabled;
		case ELEMENT_FLAG_DEFAULT:
			return ElementFlagDefault;
		case ELEMENT_FLAG_FORCED:
			return ElementFlagForced;
		case ELEMENT_FLAG_LACING:
			return ElementFlagLacing;
		case ELEMENT_DEFAULT_DURATION:
			return ElementDefaultDuration;
		case ELEMENT_NAME:
			return ElementName;
		case ELEMENT_LANGUAGE:
			return ElementLanguage;
		case ELEMENT_CODEC_ID:
			return ElementCodecID;
		case ELEMENT_CODEC_PRIVATE:
			return ElementCodecPrivate;
		case ELEMENT_CODEC_NAME:
			return ElementCodecName;
		case ELEMENT_CODEC_DELAY:
			return ElementCodecDelay;
		case ELEMENT_SEEK_PRE_ROLL:
			return ElementSeekPreRoll;
		case ELEMENT_VIDEO:
			return ElementVideo;
		case ELEMENT_FLAG_INTERLACED:
			return ElementFlagInterlaced;
		case ELEMENT_STEREO_MODE:
			return ElementStereoMode;
		case ELEMENT_ALPHA_MODE:
			return ElementAlphaMode;
		case ELEMENT_PIXEL_WIDTH:
			return ElementPixelWidth;
		case ELEMENT_PIXEL_HEIGHT:
			return ElementPixelHeight;
		case ELEMENT_PIXEL_CROP_BOTTOM:
			return ElementPixelCropBottom;
		case ELEMENT_PIXEL_CROP_TOP:
			return ElementPixelCropTop;
		case ELEMENT_PIXEL_CROP_LEFT:
			return ElementPixelCropLeft;
		case ELEMENT_PIXEL_CROP_RIGHT:
			return ElementPixelCropRight;
		case ELEMENT_DISPLAY_WIDTH:
			return ElementDisplayWidth;
		case ELEMENT_DISPLAY_HEIGHT:
			return ElementDisplayHeight;
		case ELEMENT_DISPLAY_UINT:
			return ElementDisplayUint;
		case ELEMENT_ASPECT_RATIO_TYPE:
			return ElementAspectRatioType;
		case ELEMENT_AUDIO:
			return ElementAudio;
		case ELEMENT_SAMPLING_FREQUENCY:
			return ElementSamplingFrequency;
		case ELEMENT_OUTPUT_SAMPLING_FREQUENCY:
			return ElementOutputSamplingFrequency;
		case ELEMENT_CHANNELS:
			return ElementChannels;
		case ELEMENT_BIT_DEPTH:
			return ElementBitDepth;
		case ELEMENT_CONTENT_ENCODINGS:
			return ElementContentEncodings;
		case ELEMENT_CONTENT_ENCODING:
			return ElementContentEncoding;
		case ELEMENT_CONTENT_ENCODING_ORDER:
			return ElementContentEncodingOrder;
		case ELEMENT_CONTENT_ENCODING_SCOPE:
			return ElementContentEncodingScope;
		case ELEMENT_CONTENT_ENCODING_TYPE:
			return ElementContentEncodingType;
		case ELEMENT_CONTENT_ENCRYPTION:
			return ElementContentEncryption;
		case ELEMENT_CONTENT_ENC_ALGO:
			return ElementContentEncAlgo;
		case ELEMENT_CONTENT_ENC_KEY_ID:
			return ElementContentEncKeyID;
		case ELEMENT_UNKNOWN:
			return ElementUnknown;
		default:
			return ElementUnknown;
	}
}
