#pragma once

#include <stdint.h>

#define ELEMENT_TYPE_UNKNOWN  0x0
#define ELEMENT_TYPE_MASTER   0x1
#define ELEMENT_TYPE_UINT     0x2
#define ELEMENT_TYPE_INT      0x3
#define ELEMENT_TYPE_STRING   0x4
#define ELEMENT_TYPE_UNICODE  0x5
#define ELEMENT_TYPE_BINARY   0x6
#define ELEMENT_TYPE_FLOAT    0x7
#define ELEMENT_TYPE_DATE     0x8

typedef struct {
	uint32_t id;
	uint8_t type;
	const char* name;
} mkv_register_t;

const mkv_register_t ElementUnknown                     = {0x0, ELEMENT_TYPE_UNKNOWN, "Unknown"};
const mkv_register_t ElementEBML                        = {0x1a45dfa3, ELEMENT_TYPE_MASTER, "EBML"};
const mkv_register_t ElementEBMLVersion                 = {0x4286, ELEMENT_TYPE_UINT, "EBMLVersion"};
const mkv_register_t ElementEBMLReadVersion             = {0x42f7, ELEMENT_TYPE_UINT, "EBMLReadVersion"};
const mkv_register_t ElementEBMLMaxIDLength             = {0x42f2, ELEMENT_TYPE_UINT, "EBMLMaxIDLength"};
const mkv_register_t ElementEBMLMaxSizeLength           = {0x42f3, ELEMENT_TYPE_UINT, "EBMLMaxSizeLength"};
const mkv_register_t ElementDocType                     = {0x4282, ELEMENT_TYPE_STRING, "DocType"};
const mkv_register_t ElementDocTypeVersion              = {0x4287, ELEMENT_TYPE_UINT, "DocTypeVersion"};
const mkv_register_t ElementDocTypeReadVersion          = {0x4285, ELEMENT_TYPE_UINT, "DocTypeReadVersion"};
const mkv_register_t ElementVoid                        = {0xec, ELEMENT_TYPE_BINARY, "Void"};
const mkv_register_t ElementCRC32                       = {0xbf, ELEMENT_TYPE_BINARY, "CRC-32"};
const mkv_register_t ElementSegment                     = {0x18538067, ELEMENT_TYPE_MASTER, "Segment"};
const mkv_register_t ElementSeekHead                    = {0x114d9b74, ELEMENT_TYPE_MASTER, "SeekHead"};
const mkv_register_t ElementSeek                        = {0x4dbb, ELEMENT_TYPE_MASTER, "Seek"};
const mkv_register_t ElementSeekID                      = {0x53ab, ELEMENT_TYPE_BINARY, "SeekID"};
const mkv_register_t ElementSeekPosition                = {0x53ac, ELEMENT_TYPE_UINT, "SeekPosition"};
const mkv_register_t ElementInfo                        = {0x1549a966, ELEMENT_TYPE_MASTER, "Info"};
const mkv_register_t ElementSegmentUID                  = {0x73a4, ELEMENT_TYPE_BINARY, "SegmentUID"};
const mkv_register_t ElementSegmentFilename             = {0x7384, ELEMENT_TYPE_UNICODE, "SegmentFilename"};
const mkv_register_t ElementPrevUID                     = {0x3cb923, ELEMENT_TYPE_BINARY, "PrevUID"};
const mkv_register_t ElementPrevFilename                = {0x3c83ab, ELEMENT_TYPE_UNICODE, "PrevFilename"};
const mkv_register_t ElementNextUID                     = {0x3eb923, ELEMENT_TYPE_BINARY, "NextUID"};
const mkv_register_t ElementNextFilename                = {0x3e83bb, ELEMENT_TYPE_UNICODE, "NextFilename"};
const mkv_register_t ElementSegmentFamily               = {0x4444, ELEMENT_TYPE_BINARY, "SegmentFamily"};
const mkv_register_t ElementChapterTranslate            = {0x6924, ELEMENT_TYPE_MASTER, "ChapterTranslate"};
const mkv_register_t ElementChapterTranslateEditionUID  = {0x69fc, ELEMENT_TYPE_UINT, "ChapterTranslateEditionUID"};
const mkv_register_t ElementChapterTranslateCodec       = {0x69bf, ELEMENT_TYPE_UINT, "ChapterTranslateCodec"};
const mkv_register_t ElementChapterTranslateID          = {0x69a5, ELEMENT_TYPE_BINARY, "ChapterTranslateID"};
const mkv_register_t ElementTimecodeScale               = {0x2ad7b1, ELEMENT_TYPE_UINT, "TimecodeScale"};
const mkv_register_t ElementDuration                    = {0x4489, ELEMENT_TYPE_FLOAT, "Duration"};
const mkv_register_t ElementDateUTC                     = {0x4461, ELEMENT_TYPE_DATE, "DateUTC"};
const mkv_register_t ElementTitle                       = {0x7ba9, ELEMENT_TYPE_UNICODE, "Title"};
const mkv_register_t ElementMuxingApp                   = {0x4d80, ELEMENT_TYPE_UNICODE, "MuxingApp"};
const mkv_register_t ElementWritingApp                  = {0x5741, ELEMENT_TYPE_UNICODE, "WritingApp"};
const mkv_register_t ElementCluster                     = {0x1f43b675, ELEMENT_TYPE_MASTER, "Cluster"};
const mkv_register_t ElementTimecode                    = {0xe7, ELEMENT_TYPE_UINT, "Timecode"};
const mkv_register_t ElementSlientTracks                = {0x5854, ELEMENT_TYPE_MASTER, "SlientTracks"};
const mkv_register_t ElementSlientTrackNumber           = {0x58d7, ELEMENT_TYPE_UINT, "SlientTrackNumber"};
const mkv_register_t ElementPosition                    = {0xa7, ELEMENT_TYPE_UINT, "Position"};
const mkv_register_t ElementPrevSize                    = {0xab, ELEMENT_TYPE_UINT, "PrevSize"};
const mkv_register_t ElementSimpleBlock                 = {0xa3, ELEMENT_TYPE_BINARY, "SimpleBlock"};
const mkv_register_t ElementBlockGroup                  = {0xa0, ELEMENT_TYPE_MASTER, "BlockGroup"};
const mkv_register_t ElementBlock                       = {0xa1, ELEMENT_TYPE_BINARY, "Block"};
const mkv_register_t ElementBlockAdditions              = {0x75a1, ELEMENT_TYPE_MASTER, "BlockAdditions"};
const mkv_register_t ElementBlockMore                   = {0xa6, ELEMENT_TYPE_MASTER, "BlockMore"};
const mkv_register_t ElementBlockAddID                  = {0xee, ELEMENT_TYPE_UINT, "BlockAddID"};
const mkv_register_t ElementBlockAdditional             = {0xa5, ELEMENT_TYPE_BINARY, "BlockAdditional"};
const mkv_register_t ElementBlockDuration               = {0x9b, ELEMENT_TYPE_UINT, "BlockDuration"};
const mkv_register_t ElementReferencePriority           = {0xfa, ELEMENT_TYPE_UINT, "ReferencePriority"};
const mkv_register_t ElementReferenceBlock              = {0xfb, ELEMENT_TYPE_INT, "ReferenceBlock"};
const mkv_register_t ElementCodecState                  = {0xa4, ELEMENT_TYPE_BINARY, "CodecState"};
const mkv_register_t ElementDiscardPadding              = {0x75a2, ELEMENT_TYPE_INT, "DiscardPadding"};
const mkv_register_t ElementSlices                      = {0x8e, ELEMENT_TYPE_MASTER, "Slices"};
const mkv_register_t ElementTimeSlice                   = {0xe8, ELEMENT_TYPE_MASTER, "TimeSlice"};
const mkv_register_t ElementLaceNumber                  = {0xcc, ELEMENT_TYPE_UINT, "LaceNumber"};
const mkv_register_t ElementTracks                      = {0x1654ae6b, ELEMENT_TYPE_MASTER, "Tracks"};
const mkv_register_t ElementTrackEntry                  = {0xae, ELEMENT_TYPE_MASTER, "TrackEntry"};
const mkv_register_t ElementTrackNumber                 = {0xd7, ELEMENT_TYPE_UINT, "TrackNumber"};
const mkv_register_t ElementTrackUID                    = {0x73c5, ELEMENT_TYPE_UINT, "TrackUID"};
const mkv_register_t ElementTrackType                   = {0x83, ELEMENT_TYPE_UINT, "TrackType"};
const mkv_register_t ElementFlagEnabled                 = {0xb9, ELEMENT_TYPE_UINT, "FlagEnabled"};
const mkv_register_t ElementFlagDefault                 = {0x88, ELEMENT_TYPE_UINT, "FlagDefault"};
const mkv_register_t ElementFlagForced                  = {0x55aa, ELEMENT_TYPE_UINT, "FlagForced"};
const mkv_register_t ElementFlagLacing                  = {0x9c, ELEMENT_TYPE_UINT, "FlagLacing"};
const mkv_register_t ElementMinCache                    = {0x6de7, ELEMENT_TYPE_UINT, "MinCache"};
const mkv_register_t ElementMaxCache                    = {0x6df8, ELEMENT_TYPE_UINT, "MaxCache"};
const mkv_register_t ElementDefaultDuration             = {0x23e383, ELEMENT_TYPE_UINT, "DefaultDuration"};
const mkv_register_t ElementDefaultDecodedFieldDuration = {0x234e7a, ELEMENT_TYPE_UINT, "DefaultDecodedFieldDuration"};
const mkv_register_t ElementMaxBlockAdditionID          = {0x55ee, ELEMENT_TYPE_UINT, "MaxBlockAdditionID"};
const mkv_register_t ElementName                        = {0x536e, ELEMENT_TYPE_UNICODE, "Name"};
const mkv_register_t ElementLanguage                    = {0x22b59c, ELEMENT_TYPE_STRING, "Language"};
const mkv_register_t ElementCodecID                     = {0x86, ELEMENT_TYPE_STRING, "CodecID"};
const mkv_register_t ElementCodecPrivate                = {0x63a2, ELEMENT_TYPE_BINARY, "CodecPrivate"};
const mkv_register_t ElementCodecName                   = {0x258688, ELEMENT_TYPE_UNICODE, "CodecName"};
const mkv_register_t ElementAttachmentLink              = {0x7446, ELEMENT_TYPE_UINT, "AttachmentLink"};
const mkv_register_t ElementCodecDecodeAll              = {0xaa, ELEMENT_TYPE_UINT, "CodecDecodeAll"};
const mkv_register_t ElementTrackOverlay                = {0x6fab, ELEMENT_TYPE_UINT, "TrackOverlay"};
const mkv_register_t ElementCodecDelay                  = {0x56aa, ELEMENT_TYPE_UINT, "CodecDelay"};
const mkv_register_t ElementSeekPreRoll                 = {0x56bb, ELEMENT_TYPE_UINT, "SeekPreRoll"};
const mkv_register_t ElementTrackTranslate              = {0x6624, ELEMENT_TYPE_MASTER, "TrackTranslate"};
const mkv_register_t ElementTrackTranslateEditionUID    = {0x66fc, ELEMENT_TYPE_UINT, "TrackTranslateEditionUID"};
const mkv_register_t ElementTrackTranslateCodec         = {0x66bf, ELEMENT_TYPE_UINT, "TrackTranslateCodec"};
const mkv_register_t ElementTrackTranslateTrackID       = {0x66a5, ELEMENT_TYPE_BINARY, "TrackTranslateTrackID"};
const mkv_register_t ElementVideo                       = {0xe0, ELEMENT_TYPE_MASTER, "Video"};
const mkv_register_t ElementFlagInterlaced              = {0x9a, ELEMENT_TYPE_UINT, "FlagInterlaced"};
const mkv_register_t ElementStereoMode                  = {0x53b8, ELEMENT_TYPE_UINT, "StereoMode"};
const mkv_register_t ElementAlphaMode                   = {0x53c0, ELEMENT_TYPE_UINT, "AlphaMode"};
const mkv_register_t ElementPixelWidth                  = {0xb0, ELEMENT_TYPE_UINT, "PixelWidth"};
const mkv_register_t ElementPixelHeight                 = {0xba, ELEMENT_TYPE_UINT, "PixelHeight"};
const mkv_register_t ElementPixelCropBottom             = {0x54aa, ELEMENT_TYPE_UINT, "PixelCropBottom"};
const mkv_register_t ElementPixelCropTop                = {0x54bb, ELEMENT_TYPE_UINT, "PixelCropTop"};
const mkv_register_t ElementPixelCropLeft               = {0x54cc, ELEMENT_TYPE_UINT, "PixelCropLeft"};
const mkv_register_t ElementPixelCropRight              = {0x54dd, ELEMENT_TYPE_UINT, "PixelCropRight"};
const mkv_register_t ElementDisplayWidth                = {0x54b0, ELEMENT_TYPE_UINT, "DisplayWidth"};
const mkv_register_t ElementDisplayHeight               = {0x54ba, ELEMENT_TYPE_UINT, "DisplayHeight"};
const mkv_register_t ElementDisplayUint                 = {0x54b2, ELEMENT_TYPE_UINT, "DisplayUint"};
const mkv_register_t ElementAspectRatioType             = {0x54b3, ELEMENT_TYPE_UINT, "AspectRatioType"};
const mkv_register_t ElementColourSpace                 = {0x2eb524, ELEMENT_TYPE_BINARY, "ColourSpace"};
const mkv_register_t ElementAudio                       = {0xe1, ELEMENT_TYPE_MASTER, "Audio"};
const mkv_register_t ElementSamplingFrequency           = {0xb5, ELEMENT_TYPE_FLOAT, "SamplingFrequency"};
const mkv_register_t ElementOutputSamplingFrequency     = {0x78b5, ELEMENT_TYPE_FLOAT, "OutputSamplingFrequency"};
const mkv_register_t ElementChannels                    = {0x9f, ELEMENT_TYPE_UINT, "Channels"};
const mkv_register_t ElementBitDepth                    = {0x6264, ELEMENT_TYPE_UINT, "BitDepth"};
const mkv_register_t ElementTrackOperation              = {0xe2, ELEMENT_TYPE_MASTER, "TrackOperation"};
const mkv_register_t ElementTrackCombinePlanes          = {0xe3, ELEMENT_TYPE_MASTER, "TrackCombinePlanes"};
const mkv_register_t ElementTrackPlane                  = {0xe4, ELEMENT_TYPE_MASTER, "TrackPlane"};
const mkv_register_t ElementTrackPlaneUID               = {0xe5, ELEMENT_TYPE_UINT, "TrackPlaneUID"};
const mkv_register_t ElementTrackPlaneType              = {0xe6, ELEMENT_TYPE_UINT, "TrackPlaneType"};
const mkv_register_t ElementTrackJoinBlocks             = {0xe9, ELEMENT_TYPE_MASTER, "TrackJoinBlocks"};
const mkv_register_t ElementTrackJoinUID                = {0xed, ELEMENT_TYPE_UINT, "TrackJoinUID"};
const mkv_register_t ElementContentEncodings            = {0x6d80, ELEMENT_TYPE_MASTER, "ContentEncodings"};
const mkv_register_t ElementContentEncoding             = {0x6240, ELEMENT_TYPE_MASTER, "ContentEncoding"};
const mkv_register_t ElementContentEncodingOrder        = {0x5031, ELEMENT_TYPE_UINT, "ContentEncodingOrder"};
const mkv_register_t ElementContentEncodingScope        = {0x5032, ELEMENT_TYPE_UINT, "ContentEncodingScope"};
const mkv_register_t ElementContentEncodingType         = {0x5033, ELEMENT_TYPE_UINT, "ContentEncodingType"};
const mkv_register_t ElementContentCompression          = {0x5034, ELEMENT_TYPE_MASTER, "ContentCompression"};
const mkv_register_t ElementContentCompAlgo             = {0x4254, ELEMENT_TYPE_UINT, "ContentCompAlgo"};
const mkv_register_t ElementContentCompSettings         = {0x4255, ELEMENT_TYPE_BINARY, "ContentCompSettings"};
const mkv_register_t ElementContentEncryption           = {0x5035, ELEMENT_TYPE_MASTER, "ContentEncryption"};
const mkv_register_t ElementContentEncAlgo              = {0x47e1, ELEMENT_TYPE_UINT, "ContentEncAlgo"};
const mkv_register_t ElementContentEncKeyID             = {0x47e2, ELEMENT_TYPE_UINT, "ContentEncKeyID"};
const mkv_register_t ElementContentSignature            = {0x47e3, ELEMENT_TYPE_BINARY, "ContentSignature"};
const mkv_register_t ElementContentSigKeyID             = {0x47e4, ELEMENT_TYPE_BINARY, "ContentSigKeyID"};
const mkv_register_t ElementContentSigAlgo              = {0x47e5, ELEMENT_TYPE_UINT, "ContentSigAlgo"};
const mkv_register_t ElementContentSigHashAlgo          = {0x47e6, ELEMENT_TYPE_UINT, "ContentSigHashAlgo"};
const mkv_register_t ElementCues                        = {0x1c53bb6b, ELEMENT_TYPE_MASTER, "Cues"};
const mkv_register_t ElementCuePoint                    = {0xbb, ELEMENT_TYPE_MASTER, "CuePoint"};
const mkv_register_t ElementCueTime                     = {0xb3, ELEMENT_TYPE_UINT, "CueTime"};
const mkv_register_t ElementCueTrackPositions           = {0xb7, ELEMENT_TYPE_MASTER, "CueTrackPositions"};
const mkv_register_t ElementCueTrack                    = {0xf7, ELEMENT_TYPE_UINT, "CueTrack"};
const mkv_register_t ElementCueClusterPosition          = {0xf1, ELEMENT_TYPE_UINT, "CueClusterPosition"};
const mkv_register_t ElementCueRelativePosition         = {0xf0, ELEMENT_TYPE_UINT, "CueRelativePosition"};
const mkv_register_t ElementCueDuration                 = {0xb2, ELEMENT_TYPE_UINT, "CueDuration"};
const mkv_register_t ElementCueBlockNumber              = {0x5378, ELEMENT_TYPE_UINT, "CueBlockNumber"};
const mkv_register_t ElementCueCodecState               = {0xea, ELEMENT_TYPE_UINT, "CueCodecState"};
const mkv_register_t ElementCueReference                = {0xdb, ELEMENT_TYPE_MASTER, "CueReference"};
const mkv_register_t ElementCueRefTime                  = {0x96, ELEMENT_TYPE_UINT, "CueRefTime"};
const mkv_register_t ElementAttachments                 = {0x1941a469, ELEMENT_TYPE_MASTER, "Attachments"};
const mkv_register_t ElementAttachedFile                = {0x61a7, ELEMENT_TYPE_MASTER, "AttachedFile"};
const mkv_register_t ElementFileDescription             = {0x467e, ELEMENT_TYPE_UNICODE, "FileDescription"};
const mkv_register_t ElementFileName                    = {0x466e, ELEMENT_TYPE_UNICODE, "FileName"};
const mkv_register_t ElementFileMimeType                = {0x6460, ELEMENT_TYPE_STRING, "FileMimeType"};
const mkv_register_t ElementFileData                    = {0x465c, ELEMENT_TYPE_BINARY, "FileData"};
const mkv_register_t ElementFileUID                     = {0x46ae, ELEMENT_TYPE_UINT, "FileUID"};
const mkv_register_t ElementChapters                    = {0x1043a770, ELEMENT_TYPE_MASTER, "Chapters"};
const mkv_register_t ElementEditionEntry                = {0x45b9, ELEMENT_TYPE_MASTER, "EditionEntry"};
const mkv_register_t ElementEditionUID                  = {0x45bc, ELEMENT_TYPE_UINT, "EditionUID"};
const mkv_register_t ElementEditionFlagHidden           = {0x45bd, ELEMENT_TYPE_UINT, "EditionFlagHidden"};
const mkv_register_t ElementEditionFlagDefault          = {0x45db, ELEMENT_TYPE_UINT, "EditionFlagDefault"};
const mkv_register_t ElementEditionFlagOrdered          = {0x45dd, ELEMENT_TYPE_UINT, "EditionFlagOrdered"};
const mkv_register_t ElementChapterAtom                 = {0xb6, ELEMENT_TYPE_MASTER, "ChapterAtom"};
const mkv_register_t ElementChapterUID                  = {0x73c4, ELEMENT_TYPE_UINT, "ChapterUID"};
const mkv_register_t ElementChapterStringUID            = {0x5654, ELEMENT_TYPE_UNICODE, "ChapterStringUID"};
const mkv_register_t ElementChapterTimeStart            = {0x91, ELEMENT_TYPE_UINT, "ChapterTimeStart"};
const mkv_register_t ElementChapterTimeEnd              = {0x92, ELEMENT_TYPE_UINT, "ChapterTimeEnd"};
const mkv_register_t ElementChapterFlagHidden           = {0x98, ELEMENT_TYPE_UINT, "ChapterFlagHidden"};
const mkv_register_t ElementChapterFlagEnabled          = {0x4598, ELEMENT_TYPE_UINT, "ChapterFlagEnabled"};
const mkv_register_t ElementChapterSegmentUID           = {0x6e67, ELEMENT_TYPE_BINARY, "ChapterSegmentUID"};
const mkv_register_t ElementChapterSegmentEditionUID    = {0x6ebc, ELEMENT_TYPE_UINT, "ChapterSegmentEditionUID"};
const mkv_register_t ElementChapterPhysicalEquiv        = {0x63c3, ELEMENT_TYPE_UINT, "ChapterPhysicalEquiv"};
const mkv_register_t ElementChapterTrack                = {0x8f, ELEMENT_TYPE_MASTER, "ChapterTrack"};
const mkv_register_t ElementChapterTrackNumber          = {0x89, ELEMENT_TYPE_UINT, "ChapterTrackNumber"};
const mkv_register_t ElementChapterDisplay              = {0x80, ELEMENT_TYPE_MASTER, "ChapterDisplay"};
const mkv_register_t ElementChapString                  = {0x85, ELEMENT_TYPE_UNICODE, "ChapString"};
const mkv_register_t ElementChapLanguage                = {0x437c, ELEMENT_TYPE_STRING, "ChapLanguage"};
const mkv_register_t ElementChapCountry                 = {0x437e, ELEMENT_TYPE_STRING, "ChapCountry"};
const mkv_register_t ElementChapProcess                 = {0x6944, ELEMENT_TYPE_MASTER, "ChapProcess"};
const mkv_register_t ElementChapProcessCodecID          = {0x6955, ELEMENT_TYPE_UINT, "ChapProcessCodecID"};
const mkv_register_t ElementChapProcessPrivate          = {0x450d, ELEMENT_TYPE_BINARY, "ChapProcessPrivate"};
const mkv_register_t ElementChapProcessCommand          = {0x6911, ELEMENT_TYPE_MASTER, "ChapProcessCommand"};
const mkv_register_t ElementChapProcessTime             = {0x6922, ELEMENT_TYPE_UINT, "ChapProcessTime"};
const mkv_register_t ElementChapProcessData             = {0x6933, ELEMENT_TYPE_BINARY, "ChapProcessData"};
